title: Customer Documentation

description: Comprehensive guides, API references, and release notes for your product.

remote_theme: just-the-docs/just-the-docs

url: "https://bloodstarblade.github.io"
baseurl: "/customer-docs"

search_enabled: true

nav_sort: case_insensitive

color_scheme: light

aux_links:
  "GitHub":
    - "https://github.com/Bloodstarblade/customer-docs"

footer_content: "&copy; Your Company 2026"